#!/bin/bash

do_start() {
  mvn spring-boot:run -f /vagrant/worker/pom.xml >/vagrant/worker/stdout 2> /vagrant/worker/stderr &
}
do_stop() {
  killall java
}
do_status() {
  if [[ $(ps aux|grep spring| wc -l) -ne 1 ]]; then
    echo started
  else
    echo stopped
  fi
}
case "$1" in
  start)
    do_start
    ;;
  stop)
    do_stop
    ;;
  restart)
    do_stop
    do_start
    ;;
  status)
    do_status
    ;;
  *)
    echo "Usage: $0 start|stop|restart" >&2
    exit 1
    ;;
esac